/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Restoran11;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Volkan
 */
public class Arayuz extends javax.swing.JFrame {

    public static String Mail;
    
    /**
     * Creates new form denemeler
     * @param Mail
     */
    public Arayuz(String Mail) {
        initComponents();
        loadUserProfile(Mail);
    }

    public int toplam(){
    
        return ToplamFiyat;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        Menu = new javax.swing.JPanel();
        MenuGosterPanel = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        UrunListe = new javax.swing.JScrollPane();
        UrunTablo = new javax.swing.JTable();
        MenuGosterButton = new javax.swing.JButton();
        Siparis = new javax.swing.JPanel();
        SepetPanel = new javax.swing.JPanel();
        SepetListe = new javax.swing.JScrollPane();
        SepetTablo = new javax.swing.JTable();
        ToplamYazi = new javax.swing.JLabel();
        OdemeButton = new javax.swing.JButton();
        MenuPanel1 = new javax.swing.JPanel();
        KategoriSec = new javax.swing.JComboBox<>();
        UrunListe1 = new javax.swing.JScrollPane();
        UrunTablo1 = new javax.swing.JTable();
        MenuGosterButton1 = new javax.swing.JButton();
        SepeteEkle = new javax.swing.JButton();
        Iletisim = new javax.swing.JPanel();
        hakkimizda = new javax.swing.JLabel();
        lezzet = new javax.swing.JLabel();
        calismasaatleri = new javax.swing.JLabel();
        tumgun = new javax.swing.JLabel();
        besiktas = new javax.swing.JLabel();
        numaraCem = new javax.swing.JLabel();
        iletisim = new javax.swing.JLabel();
        subelerimiz = new javax.swing.JLabel();
        basaksehir = new javax.swing.JLabel();
        numaraSongul = new javax.swing.JLabel();
        numaraVolkan = new javax.swing.JLabel();
        sultangazi = new javax.swing.JLabel();
        tuzla = new javax.swing.JLabel();
        numaraHivda = new javax.swing.JLabel();
        numaraNil = new javax.swing.JLabel();
        esenyurt = new javax.swing.JLabel();
        zoomLinki = new java.awt.Button();
        Profil = new javax.swing.JPanel();
        ad = new javax.swing.JLabel();
        soyad = new javax.swing.JLabel();
        eposta = new javax.swing.JLabel();
        telno = new javax.swing.JLabel();
        adres = new javax.swing.JLabel();
        kart = new javax.swing.JLabel();
        kartno = new javax.swing.JLabel();
        cvv = new javax.swing.JLabel();
        tarih = new javax.swing.JLabel();
        soyadgirisi = new javax.swing.JLabel();
        mailgirisi = new javax.swing.JTextField();
        telnogirisi = new javax.swing.JTextField();
        adresgirisi = new javax.swing.JTextField();
        kartnogirisi = new javax.swing.JTextField();
        cvvgirisi = new javax.swing.JTextField();
        tarihgirisi = new javax.swing.JTextField();
        bilgikaydetbutton = new javax.swing.JButton();
        profilguncelleyazisi = new javax.swing.JLabel();
        adgirisi = new javax.swing.JLabel();
        idgirisi = new javax.swing.JLabel();
        ProfilFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(800, 500));

        MenuGosterPanel.setPreferredSize(new java.awt.Dimension(800, 500));

        MenuPanel.setBackground(new java.awt.Color(0, 153, 153));
        MenuPanel.setPreferredSize(new java.awt.Dimension(800, 500));

        UrunTablo.setBackground(new java.awt.Color(204, 204, 204));
        UrunTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ÜrünID", "Ürün", "Fiyat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UrunTablo.setName(""); // NOI18N
        UrunListe.setViewportView(UrunTablo);

        MenuGosterButton.setText("Menü Göster");
        MenuGosterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGosterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(UrunListe, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MenuGosterButton)
                .addGap(350, 350, 350))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(MenuGosterButton)
                .addGap(40, 40, 40)
                .addComponent(UrunListe, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MenuGosterPanelLayout = new javax.swing.GroupLayout(MenuGosterPanel);
        MenuGosterPanel.setLayout(MenuGosterPanelLayout);
        MenuGosterPanelLayout.setHorizontalGroup(
            MenuGosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuGosterPanelLayout.createSequentialGroup()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MenuGosterPanelLayout.setVerticalGroup(
            MenuGosterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuGosterPanelLayout.createSequentialGroup()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuGosterPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addComponent(MenuGosterPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Menü", Menu);

        Siparis.setPreferredSize(new java.awt.Dimension(800, 500));

        SepetPanel.setBackground(new java.awt.Color(0, 153, 153));
        SepetPanel.setPreferredSize(new java.awt.Dimension(250, 500));

        SepetTablo.setBackground(new java.awt.Color(204, 204, 204));
        SepetTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ÜrünID", "Ürün", "Adet", "Fiyat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        SepetListe.setViewportView(SepetTablo);

        ToplamYazi.setText("Toplam: ");

        OdemeButton.setText("Ödeme Yap");
        OdemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdemeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SepetPanelLayout = new javax.swing.GroupLayout(SepetPanel);
        SepetPanel.setLayout(SepetPanelLayout);
        SepetPanelLayout.setHorizontalGroup(
            SepetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SepetListe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(SepetPanelLayout.createSequentialGroup()
                .addComponent(ToplamYazi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(OdemeButton)
                .addGap(0, 71, Short.MAX_VALUE))
        );
        SepetPanelLayout.setVerticalGroup(
            SepetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SepetPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(SepetListe, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SepetPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ToplamYazi, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OdemeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuPanel1.setBackground(new java.awt.Color(0, 153, 153));

        KategoriSec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kahvaltı", "Kebaplar", "Çorbalar", "Mezeler", "Salatalar", "Ara Sıcaklar", "Tatlılar", "İçecekler" }));
        KategoriSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KategoriSecActionPerformed(evt);
            }
        });

        UrunTablo1.setBackground(new java.awt.Color(204, 204, 204));
        UrunTablo1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ÜrünID", "Ürün", "Fiyat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        UrunTablo1.setName(""); // NOI18N
        UrunListe1.setViewportView(UrunTablo1);

        MenuGosterButton1.setText("Menü göster");
        MenuGosterButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuGosterButton1ActionPerformed(evt);
            }
        });

        SepeteEkle.setText("Sepete Ekle");
        SepeteEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SepeteEkleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanel1Layout = new javax.swing.GroupLayout(MenuPanel1);
        MenuPanel1.setLayout(MenuPanel1Layout);
        MenuPanel1Layout.setHorizontalGroup(
            MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanel1Layout.createSequentialGroup()
                .addComponent(UrunListe1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KategoriSec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(MenuGosterButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SepeteEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuPanel1Layout.setVerticalGroup(
            MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MenuPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UrunListe1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuPanel1Layout.createSequentialGroup()
                        .addComponent(KategoriSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(211, 211, 211)
                        .addComponent(MenuGosterButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SepeteEkle)))
                .addGap(128, 128, 128))
        );

        javax.swing.GroupLayout SiparisLayout = new javax.swing.GroupLayout(Siparis);
        Siparis.setLayout(SiparisLayout);
        SiparisLayout.setHorizontalGroup(
            SiparisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SiparisLayout.createSequentialGroup()
                .addComponent(MenuPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(SepetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
        );
        SiparisLayout.setVerticalGroup(
            SiparisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(SepetPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sipariş Ver", Siparis);

        Iletisim.setBackground(new java.awt.Color(0, 153, 153));

        hakkimizda.setBackground(new java.awt.Color(102, 203, 55));
        hakkimizda.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        hakkimizda.setText("Hakkımızda");
        hakkimizda.setMaximumSize(new java.awt.Dimension(100, 15));
        hakkimizda.setMinimumSize(new java.awt.Dimension(100, 15));
        hakkimizda.setPreferredSize(new java.awt.Dimension(100, 15));

        lezzet.setBackground(new java.awt.Color(51, 51, 255));
        lezzet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lezzet.setForeground(new java.awt.Color(255, 255, 255));
        lezzet.setText("İSTANBUL'DAKİ KALİTELİ YEMEKLERİ EN İYİ LEZZETLERLE SİZLERE SUNUYORUZ");

        calismasaatleri.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        calismasaatleri.setText("         Çalışma Saatlerimiz:");

        tumgun.setText("Pazartesi - Pazar: 09.00 - 00.00");

        besiktas.setText("İstanbul/Beşiktaş      ------------->");

        numaraCem.setText("+90 (553)-826-5358");

        iletisim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        iletisim.setText("İletişim");

        subelerimiz.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        subelerimiz.setText("Şubelerimiz:");

        basaksehir.setText("İstanbul/Başakşehir  ------------->");

        numaraSongul.setText("+90 (538)-304-1368");

        numaraVolkan.setText("+90 (541)-843-3412");

        sultangazi.setText("İstanbul/Sultangazi  ------------->");

        tuzla.setText("İstanbul/Tuzla          -------------->");

        numaraHivda.setText("+90 (533)-732-3149");

        numaraNil.setText("+90 (507)-730-1229");

        esenyurt.setText("İstanbul/Esenyurt     -------------->");

        zoomLinki.setActionCommand("Zoom'a Bağlanmak İçin Tıklayınız.");
        zoomLinki.setBackground(new java.awt.Color(0, 204, 204));
        zoomLinki.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        zoomLinki.setLabel("Canlı Destek");
        zoomLinki.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zoomLinkiMouseClicked(evt);
            }
        });
        zoomLinki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomLinkiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IletisimLayout = new javax.swing.GroupLayout(Iletisim);
        Iletisim.setLayout(IletisimLayout);
        IletisimLayout.setHorizontalGroup(
            IletisimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IletisimLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(IletisimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IletisimLayout.createSequentialGroup()
                        .addComponent(zoomLinki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IletisimLayout.createSequentialGroup()
                        .addGroup(IletisimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calismasaatleri, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tumgun, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(220, 220, 220))))
            .addGroup(IletisimLayout.createSequentialGroup()
                .addGroup(IletisimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IletisimLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(IletisimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(IletisimLayout.createSequentialGroup()
                                .addGroup(IletisimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sultangazi, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(basaksehir))
                                .addGap(18, 18, 18)
                                .addGroup(IletisimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(numaraVolkan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(numaraSongul)))
                            .addGroup(IletisimLayout.createSequentialGroup()
                                .addComponent(tuzla, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(numaraHivda))
                            .addGroup(IletisimLayout.createSequentialGroup()
                                .addComponent(esenyurt)
                                .addGap(20, 20, 20)
                                .addComponent(numaraNil))
                            .addGroup(IletisimLayout.createSequentialGroup()
                                .addComponent(besiktas)
                                .addGap(22, 22, 22)
                                .addComponent(numaraCem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(IletisimLayout.createSequentialGroup()
                        .addGap(303, 303, 303)
                        .addComponent(hakkimizda, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(IletisimLayout.createSequentialGroup()
                .addGroup(IletisimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IletisimLayout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(subelerimiz)
                        .addGap(151, 151, 151)
                        .addComponent(iletisim))
                    .addGroup(IletisimLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(lezzet)))
                .addGap(0, 178, Short.MAX_VALUE))
        );
        IletisimLayout.setVerticalGroup(
            IletisimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IletisimLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(hakkimizda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lezzet, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(calismasaatleri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tumgun)
                .addGap(18, 18, 18)
                .addGroup(IletisimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subelerimiz)
                    .addComponent(iletisim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IletisimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numaraCem, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(besiktas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IletisimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basaksehir)
                    .addComponent(numaraSongul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IletisimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numaraVolkan)
                    .addComponent(sultangazi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IletisimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tuzla)
                    .addComponent(numaraHivda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(IletisimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numaraNil)
                    .addComponent(esenyurt))
                .addGap(47, 47, 47)
                .addComponent(zoomLinki, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab(" İletişim", Iletisim);

        Profil.setBackground(new java.awt.Color(0, 153, 153));
        Profil.setPreferredSize(new java.awt.Dimension(800, 500));

        ad.setBackground(new java.awt.Color(204, 204, 255));
        ad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ad.setText("Adınız:");

        soyad.setBackground(new java.awt.Color(204, 204, 255));
        soyad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        soyad.setText("Soyadınız:");

        eposta.setBackground(new java.awt.Color(204, 204, 255));
        eposta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        eposta.setText("E-posta Adresiniz:");

        telno.setBackground(new java.awt.Color(204, 204, 255));
        telno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        telno.setText("Telefon numaranız:");

        adres.setBackground(new java.awt.Color(204, 204, 255));
        adres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        adres.setText("Adresiniz: ");

        kart.setBackground(new java.awt.Color(204, 204, 255));
        kart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kart.setText("Kart Bilgileriniz:");

        kartno.setBackground(new java.awt.Color(204, 204, 255));
        kartno.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        kartno.setText("Kart numaranız:");

        cvv.setBackground(new java.awt.Color(204, 204, 255));
        cvv.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        cvv.setText("CVV Kodu:");

        tarih.setBackground(new java.awt.Color(204, 204, 255));
        tarih.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        tarih.setText("Geçerlilik Tarihi:");

        soyadgirisi.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        telnogirisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telnogirisiActionPerformed(evt);
            }
        });

        tarihgirisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarihgirisiActionPerformed(evt);
            }
        });

        bilgikaydetbutton.setText("Kaydet");
        bilgikaydetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgikaydetbuttonActionPerformed(evt);
            }
        });

        profilguncelleyazisi.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        profilguncelleyazisi.setForeground(new java.awt.Color(51, 204, 255));
        profilguncelleyazisi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profilguncelleyazisi.setText("PROFİL GÜNCELLEME");

        adgirisi.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N

        ProfilFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/user-profile-icon-free-vector.jpg"))); // NOI18N
        ProfilFoto.setText("jLabel1");

        javax.swing.GroupLayout ProfilLayout = new javax.swing.GroupLayout(Profil);
        Profil.setLayout(ProfilLayout);
        ProfilLayout.setHorizontalGroup(
            ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ProfilLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(ProfilFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfilLayout.createSequentialGroup()
                        .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kart)
                            .addGroup(ProfilLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ProfilLayout.createSequentialGroup()
                                        .addComponent(kartno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(kartnogirisi))
                                    .addGroup(ProfilLayout.createSequentialGroup()
                                        .addComponent(tarih)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tarihgirisi, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(ProfilLayout.createSequentialGroup()
                                        .addComponent(cvv)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cvvgirisi, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProfilLayout.createSequentialGroup()
                                    .addComponent(ad)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(adgirisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProfilLayout.createSequentialGroup()
                                    .addComponent(soyad)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(soyadgirisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProfilLayout.createSequentialGroup()
                                    .addComponent(telno)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(telnogirisi))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProfilLayout.createSequentialGroup()
                                    .addComponent(adres)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(adresgirisi))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ProfilLayout.createSequentialGroup()
                                    .addComponent(eposta)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mailgirisi, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ProfilLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(bilgikaydetbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ProfilLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idgirisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(profilguncelleyazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        ProfilLayout.setVerticalGroup(
            ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ProfilLayout.createSequentialGroup()
                .addComponent(profilguncelleyazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ProfilLayout.createSequentialGroup()
                        .addComponent(idgirisi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bilgikaydetbutton)
                        .addGap(150, 150, 150))
                    .addGroup(ProfilLayout.createSequentialGroup()
                        .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(ProfilLayout.createSequentialGroup()
                                .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adgirisi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(5, 5, 5)
                                .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(soyad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(soyadgirisi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(eposta, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(mailgirisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(telno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(telnogirisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(adres, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(adresgirisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(kart, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ProfilFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kartno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kartnogirisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cvv, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cvvgirisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tarihgirisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(148, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Profilim", Profil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telnogirisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telnogirisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telnogirisiActionPerformed

    private void tarihgirisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarihgirisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarihgirisiActionPerformed

    private void zoomLinkiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zoomLinkiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_zoomLinkiMouseClicked

    private void zoomLinkiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomLinkiActionPerformed
        JOptionPane.showMessageDialog(null, "!ÖNEMLİ! Zoom Toplantı Parolası: Cevhers");
        try {
            String zoomLink = "https://us05web.zoom.us/j/83231531596?pwd=typa05aibnklCiJwCNGHYtm7Kpj42f.1";
            java.awt.Desktop.getDesktop().browse(new java.net.URI(zoomLink));
        } catch (Exception e) {
            e.printStackTrace(); // Hata ayıklamak için hatayı terminale yazdırır
        }
    }//GEN-LAST:event_zoomLinkiActionPerformed

    private void bilgikaydetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgikaydetbuttonActionPerformed
        try {
            // TODO add your handling code here:
            connection = DriverManager.getConnection(baglanti.dbUrl, baglanti.username, baglanti.password);
            // Verileri al
            String id = idgirisi.getText();
            String mail = mailgirisi.getText();
            String telNo = telnogirisi.getText();
            String Adres = adresgirisi.getText();
            String kartNo = kartnogirisi.getText();
            String Cvv = cvvgirisi.getText();
            String Skt = tarihgirisi.getText();
    
            // Veritabanına kaydet
            if (saveUserData(mail, telNo, Adres, kartNo, Cvv, Skt, id)) {
                JOptionPane.showMessageDialog(null, "Bilgiler başarıyla Güncellendi.");
            } else {
                JOptionPane.showMessageDialog(null, "Bilgiler Güncellenemedi.");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Arayuz.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_bilgikaydetbuttonActionPerformed
        Connection connection=null;
        ResultSet rs=null;
        PreparedStatement pst=null;
        ArrayList<Urun> sepet = new ArrayList<>();
        int ToplamFiyat = 0;
    
    public void Update_table(){
        String secilenKategori = KategoriSec.getSelectedItem().toString();
        try
        {
        String dbURL = "jdbc:mysql://localhost:3306/restoran";
        String dbUser = "root"; 
        String dbPassword = "";
        Connection con = DriverManager.getConnection(dbURL, dbUser, dbPassword);
        String sql="select urunId,urun,fiyat from menu where kategori = '" + secilenKategori + "' ";
        
        pst=con.prepareStatement(sql);
        rs=pst.executeQuery(sql);
        UrunTablo1.setModel(ResultSetToTableModel.resultSetToTableModel(rs));
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
        
    public void Update_table_menu(){
        
        try
        {
        String dbURL = "jdbc:mysql://localhost:3306/restoran";
        String dbUser = "root"; 
        String dbPassword = "";
        Connection con = DriverManager.getConnection(dbURL, dbUser, dbPassword);
        String sql="select urunId,urun,fiyat from menu ";
        
        pst=con.prepareStatement(sql);
        rs=pst.executeQuery(sql);
        UrunTablo.setModel(ResultSetToTableModel.resultSetToTableModel(rs));
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }    
    private void OdemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdemeButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        String toplam = ToplamYazi.getText(); // Sepetdeki JLabel'dan metni aldım
        Odeme odeme = new Odeme(toplam);
        odeme.setVisible(true);
        odeme.setLocationRelativeTo(null);
        add(ToplamYazi);

    }//GEN-LAST:event_OdemeButtonActionPerformed

    private void KategoriSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KategoriSecActionPerformed
        
    }//GEN-LAST:event_KategoriSecActionPerformed

    private void MenuGosterButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGosterButton1ActionPerformed
        Update_table();
    }//GEN-LAST:event_MenuGosterButton1ActionPerformed
    
    public void SepeteEkle() {
        
    int selectedRow = UrunTablo1.getSelectedRow();
    if (selectedRow != -1) {
        String ad = (String) UrunTablo1.getValueAt(selectedRow, 1); // Ürün adı (1. sütun)
        int fiyat = (int) UrunTablo1.getValueAt(selectedRow, 2); // Fiyat (2. sütun)
        int urunId = (int) UrunTablo1.getValueAt(selectedRow, 0); // Ürün ID'si (0. sütun)
        
        boolean urunVar = false;
        
        DefaultTableModel sepetTabloModel = (DefaultTableModel) SepetTablo.getModel();
        for (int i = 0; i < SepetTablo.getRowCount(); i++) {
            int mevcutUrunId = (int) SepetTablo.getValueAt(i, 0); // Sepetteki ürünün ID'si
            if (mevcutUrunId == urunId) {
                int mevcutAdet = (int) SepetTablo.getValueAt(i, 2); // Mevcut adet
                sepetTabloModel.setValueAt(mevcutAdet + 1, i, 2); // Adet artışı
                urunVar = true;
                break;
            }
        }
        
        if (!urunVar) {

            sepetTabloModel.addRow(new Object[]{urunId, ad, 1, fiyat}); 
        }

        ToplamFiyat += fiyat;
        ToplamYazi.setText("Toplam Fiyat: " + ToplamFiyat + "TL");

        JOptionPane.showMessageDialog(null, ad + " sepete eklendi!");
        } else {
        JOptionPane.showMessageDialog(null, "Lütfen bir ürün seçin!");
        }
    }

    
    public void ToplamFiyat(){
        int selectedRow = SepetTablo.getSelectedRow();
        int Toplam = 0;
        
            if (selectedRow != -1) {
                for(int i = 0; i < SepetTablo.getRowCount();i++){
                int fiyat = (int) SepetTablo.getValueAt(selectedRow, 2); 
                Toplam+=fiyat;
                
                }
                ToplamYazi.setText("Toplam: "+Toplam);
            }
    }
    private void SepeteEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SepeteEkleActionPerformed
        SepeteEkle();
    }//GEN-LAST:event_SepeteEkleActionPerformed

    private void MenuGosterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuGosterButtonActionPerformed
        // TODO add your handling code here:
        Update_table_menu();
    }//GEN-LAST:event_MenuGosterButtonActionPerformed
    
    // Kullanıcı verilerini veritabanına kaydetme
    private boolean saveUserData(String mail, String telNo, String adres, String kartNo, String cvv, String skt, String id) {
    try {
        // Veritabanı bağlantısı
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/restoran", "root", "");

        String query = "UPDATE kullanicilar SET mail = ?, telNo = ?, adres = ?, kartNo = ?, cvv = ?, skt = ? WHERE id = ?";
        PreparedStatement ps = connection.prepareStatement(query);
        telNo = telnogirisi.getText().replaceAll("[^0-9]", "");
        kartNo = kartnogirisi.getText().replaceAll("[^0-9]", "");
        cvv = cvvgirisi.getText().replaceAll("[^0-9]", "");
        skt = tarihgirisi.getText().replaceAll("[^0-9]", "");
        ps.setString(1, mail);
        ps.setString(2, telNo);
        ps.setString(3, adres);
        ps.setString(4, kartNo);
        ps.setString(5, cvv);
        ps.setString(6, skt);
        ps.setString(7, id); 

        int rowsAffected = ps.executeUpdate();
        System.out.println("Güncellenen satır sayısı: " + rowsAffected);
        return rowsAffected > 0;
        
    } catch (SQLException ex) {
        ex.printStackTrace(); 
        JOptionPane.showMessageDialog(null, "Veritabanı hatası: " + ex.getMessage());  
        return false;  
    }
}

    
    // Kullanıcı bilgilerini veritabanından çekme
    private void loadUserProfile(String Mail) {
    try {
        // Veritabanı bağlantısı
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/restoran", "root", "");
        String query = "SELECT * FROM kullanicilar WHERE mail = ?";
        PreparedStatement ps = connection.prepareStatement(query);
        ps.setString(1, Mail);
        ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            adgirisi.setText(rs.getString("ad"));
            soyadgirisi.setText(rs.getString("soyad"));
            mailgirisi.setText(rs.getString("mail"));
            telnogirisi.setText(rs.getString("telNo"));
            adresgirisi.setText(rs.getString("adres"));
            kartnogirisi.setText(rs.getString("kartNo"));
            cvvgirisi.setText(rs.getString("cvv"));
            tarihgirisi.setText(rs.getString("skt"));
            idgirisi.setText(rs.getString("id"));
        } else {
            JOptionPane.showMessageDialog(null, "Kullanıcı Bulunamadı.");
        }
    } catch (SQLException ex) {
        ex.printStackTrace();  // Hata mesajını yazdır
        JOptionPane.showMessageDialog(null, "Kullanıcı Yükleme Hatası: " + ex.getMessage());
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Arayuz(Mail).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Iletisim;
    private javax.swing.JComboBox<String> KategoriSec;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton MenuGosterButton;
    private javax.swing.JButton MenuGosterButton1;
    private javax.swing.JPanel MenuGosterPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel MenuPanel1;
    private javax.swing.JButton OdemeButton;
    private javax.swing.JPanel Profil;
    private javax.swing.JLabel ProfilFoto;
    private javax.swing.JScrollPane SepetListe;
    private javax.swing.JPanel SepetPanel;
    private javax.swing.JTable SepetTablo;
    private javax.swing.JButton SepeteEkle;
    private javax.swing.JPanel Siparis;
    private javax.swing.JLabel ToplamYazi;
    private javax.swing.JScrollPane UrunListe;
    private javax.swing.JScrollPane UrunListe1;
    private javax.swing.JTable UrunTablo;
    private javax.swing.JTable UrunTablo1;
    private javax.swing.JLabel ad;
    private javax.swing.JLabel adgirisi;
    private javax.swing.JLabel adres;
    private javax.swing.JTextField adresgirisi;
    private javax.swing.JLabel basaksehir;
    private javax.swing.JLabel besiktas;
    private javax.swing.JButton bilgikaydetbutton;
    private javax.swing.JLabel calismasaatleri;
    private javax.swing.JLabel cvv;
    private javax.swing.JTextField cvvgirisi;
    private javax.swing.JLabel eposta;
    private javax.swing.JLabel esenyurt;
    private javax.swing.JLabel hakkimizda;
    private javax.swing.JLabel idgirisi;
    private javax.swing.JLabel iletisim;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel kart;
    private javax.swing.JLabel kartno;
    private javax.swing.JTextField kartnogirisi;
    private javax.swing.JLabel lezzet;
    private javax.swing.JTextField mailgirisi;
    private javax.swing.JLabel numaraCem;
    private javax.swing.JLabel numaraHivda;
    private javax.swing.JLabel numaraNil;
    private javax.swing.JLabel numaraSongul;
    private javax.swing.JLabel numaraVolkan;
    private javax.swing.JLabel profilguncelleyazisi;
    private javax.swing.JLabel soyad;
    private javax.swing.JLabel soyadgirisi;
    private javax.swing.JLabel subelerimiz;
    private javax.swing.JLabel sultangazi;
    private javax.swing.JLabel tarih;
    private javax.swing.JTextField tarihgirisi;
    private javax.swing.JLabel telno;
    private javax.swing.JTextField telnogirisi;
    private javax.swing.JLabel tumgun;
    private javax.swing.JLabel tuzla;
    private java.awt.Button zoomLinki;
    // End of variables declaration//GEN-END:variables
}
