/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Restoran11;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author Volkan
 */
public class Odeme extends javax.swing.JFrame {

    /**
     * Creates new form Odeme
     */
    public Odeme() {
        initComponents();
    }
    
    public Odeme(String toplam) {
        initComponents();
        Yazi.setText(toplam);
        KapikartButton.setVisible(false);
        KartButton.setVisible(false);
        NakitButton.setVisible(false);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OdemePanel = new javax.swing.JPanel();
        Yazi = new javax.swing.JLabel();
        OdemeButton = new javax.swing.JButton();
        KartButton = new javax.swing.JButton();
        NakitButton = new javax.swing.JButton();
        KapikartButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        OdemePanel.setBackground(new java.awt.Color(0, 153, 153));

        Yazi.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Yazi.setText("Toplam:");

        OdemeButton.setText("Ödeme yap");
        OdemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdemeButtonActionPerformed(evt);
            }
        });

        KartButton.setText("Kredi/Banka Kartı");
        KartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KartButtonActionPerformed(evt);
            }
        });

        NakitButton.setText("Nakit");
        NakitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NakitButtonActionPerformed(evt);
            }
        });

        KapikartButton.setText("Kapıda Kredi/Banka Kartı");

        javax.swing.GroupLayout OdemePanelLayout = new javax.swing.GroupLayout(OdemePanel);
        OdemePanel.setLayout(OdemePanelLayout);
        OdemePanelLayout.setHorizontalGroup(
            OdemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OdemePanelLayout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(OdemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(OdemeButton)
                    .addComponent(Yazi, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, OdemePanelLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(KartButton)
                .addGap(103, 103, 103)
                .addComponent(NakitButton)
                .addGap(103, 103, 103)
                .addComponent(KapikartButton)
                .addGap(116, 116, 116))
        );
        OdemePanelLayout.setVerticalGroup(
            OdemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OdemePanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(OdemeButton)
                .addGap(38, 38, 38)
                .addComponent(Yazi, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(OdemePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KartButton)
                    .addComponent(NakitButton)
                    .addComponent(KapikartButton))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OdemePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OdemePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OdemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdemeButtonActionPerformed
        // TODO add your handling code here:
        KapikartButton.setVisible(true);
        KartButton.setVisible(true);
        NakitButton.setVisible(true);
    }//GEN-LAST:event_OdemeButtonActionPerformed

    private void KartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KartButtonActionPerformed
        // TODO add your handling code here:
        
         
    }//GEN-LAST:event_KartButtonActionPerformed

    private void NakitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NakitButtonActionPerformed
        // TODO add your handling code here:,
        String text = Yazi.getText();
        Pattern pattern = Pattern.compile("\\d+");
        Matcher matcher = pattern.matcher(text);
        if (matcher.find()) {
            String number = matcher.group();
            int odeme = Integer.parseInt(number);
            JOptionPane.showMessageDialog(null, odeme+"TL Nakit ödemeniz tamamlandı iyi günler dileriz :)"
                + "Ana Menüye Yönlendiriliyorsunuz...");
            System.out.println("Toplam Fiyat: " + odeme);
            dispose();
            
        } else { JOptionPane.showMessageDialog(null, "Ödeme bilgileriniz alınamadı. "); }

    }//GEN-LAST:event_NakitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Odeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Odeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Odeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Odeme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Odeme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton KapikartButton;
    private javax.swing.JButton KartButton;
    private javax.swing.JButton NakitButton;
    private javax.swing.JButton OdemeButton;
    private javax.swing.JPanel OdemePanel;
    private javax.swing.JLabel Yazi;
    // End of variables declaration//GEN-END:variables

    
}
